### ISSUE TITLE
Update Legacy Sites to use new embeddable forms

### ISSUE THREAD

**Issue by mikegillis677** [gmo/gmocast#2]
Update our legacy websites that are currently using GMOCast embeddable forms to use the new Godlife embeddable forms.

As part of this, contact any partners that may also need to migrate.

**Comment by justinmiller24** [comment]
@mikegillis677 status update?

I'm assuming this is related to the other ticket

**Comment by mikegillis677** [comment]
@justinmiller24 It was deferred until we got the new Godlife servers deployed.  Since that finished yesterday, I was considering deploying this today.
